/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiBillingIndexRouteImport } from './routes/api/billing/index'
import { Route as ApiBillingAnalysisRouteImport } from './routes/api/billing/analysis'
import { Route as ApiBillingUploadRouteImport } from './routes/api/billing/upload'
import { Route as ApiCorrelationAnalyzeRouteImport } from './routes/api/correlation/analyze'
import { Route as ApiGithubCommitsRouteImport } from './routes/api/github/commits'
import { Route as ApiGithubConnectRouteImport } from './routes/api/github/connect'
import { Route as ApiGithubSyncRouteImport } from './routes/api/github/sync'
import { Route as ApiInsightsIndexRouteImport } from './routes/api/insights/index'
import { Route as ApiInsightsGenerateRouteImport } from './routes/api/insights/generate'
import { Route as ApiOrganizationsIndexRouteImport } from './routes/api/organizations/index'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as AppOrganizationsIndexRouteImport } from './routes/app/organizations/index'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppProjectsIdRouteImport } from './routes/app/projects/$id'
import { Route as ApiProjectsProjectIdExportRouteImport } from './routes/api/projects/$projectId/export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingIndexRoute = ApiBillingIndexRouteImport.update({
  id: '/api/billing/',
  path: '/api/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingAnalysisRoute = ApiBillingAnalysisRouteImport.update({
  id: '/api/billing/analysis',
  path: '/api/billing/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingUploadRoute = ApiBillingUploadRouteImport.update({
  id: '/api/billing/upload',
  path: '/api/billing/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorrelationAnalyzeRoute = ApiCorrelationAnalyzeRouteImport.update({
  id: '/api/correlation/analyze',
  path: '/api/correlation/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCommitsRoute = ApiGithubCommitsRouteImport.update({
  id: '/api/github/commits',
  path: '/api/github/commits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSyncRoute = ApiGithubSyncRouteImport.update({
  id: '/api/github/sync',
  path: '/api/github/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsIndexRoute = ApiInsightsIndexRouteImport.update({
  id: '/api/insights/',
  path: '/api/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsGenerateRoute = ApiInsightsGenerateRouteImport.update({
  id: '/api/insights/generate',
  path: '/api/insights/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationsIndexRoute = ApiOrganizationsIndexRouteImport.update({
  id: '/api/organizations/',
  path: '/api/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/api/projects/$id',
  path: '/api/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiProjectsProjectIdExportRoute =
  ApiProjectsProjectIdExportRouteImport.update({
    id: '/api/projects/$projectId/export',
    path: '/api/projects/$projectId/export',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/billing/analysis': typeof ApiBillingAnalysisRoute
  '/api/billing/upload': typeof ApiBillingUploadRoute
  '/api/correlation/analyze': typeof ApiCorrelationAnalyzeRoute
  '/api/github/commits': typeof ApiGithubCommitsRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/sync': typeof ApiGithubSyncRoute
  '/api/insights/generate': typeof ApiInsightsGenerateRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/api/billing/': typeof ApiBillingIndexRoute
  '/api/insights/': typeof ApiInsightsIndexRoute
  '/api/organizations/': typeof ApiOrganizationsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/billing/analysis': typeof ApiBillingAnalysisRoute
  '/api/billing/upload': typeof ApiBillingUploadRoute
  '/api/correlation/analyze': typeof ApiCorrelationAnalyzeRoute
  '/api/github/commits': typeof ApiGithubCommitsRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/sync': typeof ApiGithubSyncRoute
  '/api/insights/generate': typeof ApiInsightsGenerateRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/api/billing': typeof ApiBillingIndexRoute
  '/api/insights': typeof ApiInsightsIndexRoute
  '/api/organizations': typeof ApiOrganizationsIndexRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/app/organizations': typeof AppOrganizationsIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/billing/analysis': typeof ApiBillingAnalysisRoute
  '/api/billing/upload': typeof ApiBillingUploadRoute
  '/api/correlation/analyze': typeof ApiCorrelationAnalyzeRoute
  '/api/github/commits': typeof ApiGithubCommitsRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/sync': typeof ApiGithubSyncRoute
  '/api/insights/generate': typeof ApiInsightsGenerateRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/api/billing/': typeof ApiBillingIndexRoute
  '/api/insights/': typeof ApiInsightsIndexRoute
  '/api/organizations/': typeof ApiOrganizationsIndexRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/company'
    | '/contact'
    | '/platform'
    | '/pricing'
    | '/sitemap.xml'
    | '/solutions'
    | '/admin/organizations'
    | '/admin/projects'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/admin/'
    | '/app/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/billing/analysis'
    | '/api/billing/upload'
    | '/api/correlation/analyze'
    | '/api/github/commits'
    | '/api/github/connect'
    | '/api/github/sync'
    | '/api/insights/generate'
    | '/api/projects/$id'
    | '/app/projects/$id'
    | '/api/billing/'
    | '/api/insights/'
    | '/api/organizations/'
    | '/api/projects/'
    | '/app/organizations/'
    | '/app/projects/'
    | '/api/projects/$projectId/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/contact'
    | '/platform'
    | '/pricing'
    | '/sitemap.xml'
    | '/solutions'
    | '/admin/organizations'
    | '/admin/projects'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/admin'
    | '/app'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/billing/analysis'
    | '/api/billing/upload'
    | '/api/correlation/analyze'
    | '/api/github/commits'
    | '/api/github/connect'
    | '/api/github/sync'
    | '/api/insights/generate'
    | '/api/projects/$id'
    | '/app/projects/$id'
    | '/api/billing'
    | '/api/insights'
    | '/api/organizations'
    | '/api/projects'
    | '/app/organizations'
    | '/app/projects'
    | '/api/projects/$projectId/export'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/company'
    | '/contact'
    | '/platform'
    | '/pricing'
    | '/sitemap.xml'
    | '/solutions'
    | '/admin/organizations'
    | '/admin/projects'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/admin/'
    | '/app/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/billing/analysis'
    | '/api/billing/upload'
    | '/api/correlation/analyze'
    | '/api/github/commits'
    | '/api/github/connect'
    | '/api/github/sync'
    | '/api/insights/generate'
    | '/api/projects/$id'
    | '/app/projects/$id'
    | '/api/billing/'
    | '/api/insights/'
    | '/api/organizations/'
    | '/api/projects/'
    | '/app/organizations/'
    | '/app/projects/'
    | '/api/projects/$projectId/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiBillingAnalysisRoute: typeof ApiBillingAnalysisRoute
  ApiBillingUploadRoute: typeof ApiBillingUploadRoute
  ApiCorrelationAnalyzeRoute: typeof ApiCorrelationAnalyzeRoute
  ApiGithubCommitsRoute: typeof ApiGithubCommitsRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubSyncRoute: typeof ApiGithubSyncRoute
  ApiInsightsGenerateRoute: typeof ApiInsightsGenerateRoute
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
  ApiBillingIndexRoute: typeof ApiBillingIndexRoute
  ApiInsightsIndexRoute: typeof ApiInsightsIndexRoute
  ApiOrganizationsIndexRoute: typeof ApiOrganizationsIndexRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
  ApiProjectsProjectIdExportRoute: typeof ApiProjectsProjectIdExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/': {
      id: '/api/billing/'
      path: '/api/billing'
      fullPath: '/api/billing/'
      preLoaderRoute: typeof ApiBillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/analysis': {
      id: '/api/billing/analysis'
      path: '/api/billing/analysis'
      fullPath: '/api/billing/analysis'
      preLoaderRoute: typeof ApiBillingAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/upload': {
      id: '/api/billing/upload'
      path: '/api/billing/upload'
      fullPath: '/api/billing/upload'
      preLoaderRoute: typeof ApiBillingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/correlation/analyze': {
      id: '/api/correlation/analyze'
      path: '/api/correlation/analyze'
      fullPath: '/api/correlation/analyze'
      preLoaderRoute: typeof ApiCorrelationAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/commits': {
      id: '/api/github/commits'
      path: '/api/github/commits'
      fullPath: '/api/github/commits'
      preLoaderRoute: typeof ApiGithubCommitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/sync': {
      id: '/api/github/sync'
      path: '/api/github/sync'
      fullPath: '/api/github/sync'
      preLoaderRoute: typeof ApiGithubSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights/': {
      id: '/api/insights/'
      path: '/api/insights'
      fullPath: '/api/insights/'
      preLoaderRoute: typeof ApiInsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights/generate': {
      id: '/api/insights/generate'
      path: '/api/insights/generate'
      fullPath: '/api/insights/generate'
      preLoaderRoute: typeof ApiInsightsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/': {
      id: '/api/organizations/'
      path: '/api/organizations'
      fullPath: '/api/organizations/'
      preLoaderRoute: typeof ApiOrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects/'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/organizations/': {
      id: '/app/organizations/'
      path: '/organizations'
      fullPath: '/app/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/projects/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/projects/$projectId/export': {
      id: '/api/projects/$projectId/export'
      path: '/api/projects/$projectId/export'
      fullPath: '/api/projects/$projectId/export'
      preLoaderRoute: typeof ApiProjectsProjectIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiBillingAnalysisRoute: ApiBillingAnalysisRoute,
  ApiBillingUploadRoute: ApiBillingUploadRoute,
  ApiCorrelationAnalyzeRoute: ApiCorrelationAnalyzeRoute,
  ApiGithubCommitsRoute: ApiGithubCommitsRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubSyncRoute: ApiGithubSyncRoute,
  ApiInsightsGenerateRoute: ApiInsightsGenerateRoute,
  ApiProjectsIdRoute: ApiProjectsIdRoute,
  ApiBillingIndexRoute: ApiBillingIndexRoute,
  ApiInsightsIndexRoute: ApiInsightsIndexRoute,
  ApiOrganizationsIndexRoute: ApiOrganizationsIndexRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
  ApiProjectsProjectIdExportRoute: ApiProjectsProjectIdExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
